#!/bin/sh

# Arguments
PID=$1
EXPECTED_CMD=$2

# Defaults
PROCSTAT_CMD=/usr/bin/procstat

# Verify options passed in
if [ -z "${PID}" ] || [ -z "${EXPECTED_CMD}" ]
then
  echo "usage: check_procstat [pid] [cmd]"
  exit 1
fi

# Get the procstat output
PROCSTAT=`${PROCSTAT_CMD} -h -c ${PID}`
PROCSTAT_STATUS=$?

# Verify results
if [ -z "${PROCSTAT}" ] || [ ${PROCSTAT_STATUS} -ne 0 ] 
then
  echo "CRITICAL: ${EXPECTED_CMD}: ${PID} not found"
  exit 2
fi

# Parse the command name from the output
ACTUAL_CMD=`echo ${PROCSTAT} | awk '{print $2}'`

# Verify disk is reported as mounted by zfs
if [ "${ACTUAL_CMD}" != "${EXPECTED_CMD}" ]
then
  echo "CRITICAL: ${EXPECTED_CMD}: ${PID} doest not match: ${ACTUAL_CMD}"
  exit 2
fi

# Finally, display success
echo "OK: ${EXPECTED_CMD} running: ${PID}"
exit 0

